from pydantic import BaseModel
from typing import Optional
from datetime import date, datetime


class EmployeeBase(BaseModel):
    first_name: str
    last_name: str
    department: str
    designation: str
    date_of_joining: date
    basic_salary: float = 0.0
    phone: Optional[str] = None
    address: Optional[str] = None


class EmployeeCreate(EmployeeBase):
    """No emp_code, no password — both are auto-generated by the backend."""
    email: Optional[str] = None


class EmployeeUpdate(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    department: Optional[str] = None
    designation: Optional[str] = None
    basic_salary: Optional[float] = None
    phone: Optional[str] = None
    address: Optional[str] = None


class EmployeeResponse(EmployeeBase):
    id: int
    user_id: int
    emp_code: str
    created_at: datetime

    class Config:
        from_attributes = True


class EmployeeWithUser(EmployeeResponse):
    user_email: Optional[str] = None
    user_role: Optional[str] = None
    is_active: Optional[bool] = None


class EmployeeCreatedResponse(EmployeeResponse):
    """Returned only on creation — includes the generated credentials for sharing."""
    user_email: Optional[str] = None
    user_role: Optional[str] = None
    is_active: Optional[bool] = None
    generated_password: str  # plaintext — shown once for sharing
